Major refactor
Sxvxgee/DankCord pull request #17
Opened 2022-12-12 15:03 UTC by ThePrivatePanda

Basically, everything has changed.

## WARNING:
#### This does not update the usage of the new implementation of `ws_cache` and all command run functions as well as any relevant handling functions **WILL NOT WORK**. This will be implemented in a future PR.

Different logger.
Proper error handling everywhere.
Complete rework of ws_cache (not called gateway.cache).
Create `Config` class for initialization of bot.
Add `resource_intensivity` flag in config
- `DISK` or `MEM`- Current difference is only in how `command_data` is stored.

Added new exceptions.
Added handling for websocket reconnection
Better `recv_handler` for websocket messages.

Example of new logging output:
![image](https://user-images.githubusercontent.com/86164003/207079855-672deef6-0c05-4a08-9969-a92c7fcc2a12.png)

2022-12-12 15:39 UTC, splewdge approved these changes

2022-12-12 15:42 UTC, Sxvxgee commented
Currently going to the gym, will start a review once I'm home.

2022-12-13 09:43 UTC, Sxvxgee requested changes

2022-12-13 09:43 UTC, Sxvxgee commented on pyproject.toml
> +requires-python = ">=3.8"
I suggest you change it to python 3.11

2022-12-13 10:46 UTC, theAbdoSabbagh approved these changes

2022-12-13 10:46 UTC, merged