Command Message Parsing & Improvements to the Core Functions
Sxvxgee/DankCord pull request #24
Opened 2022-12-31 07:16 UTC by iylun

This PR adds parsing for the core functions, as well as additional parameters for the core functions like the `postmemes` function, where I added support for specifying the meme platform and type instead of needing the user to do it themself.
The parser is located in `Objects.py`, and returns the coins/items gained, success and it shows the cooldown time (if there is one). Unfortunately, I haven't added support for checking deaths but that should be added in a future PR.

2023-01-01 10:02 UTC, Sxvxgee requested changes

2023-01-01 10:02 UTC, theAbdoSabbagh commented on src/DankCord/Objects.py
> +        self.label: str = data["label"]
Why did u remove the `.get()` function? without it, a KeyError exception might be raised

2023-01-01 10:02 UTC, theAbdoSabbagh commented on src/DankCord/Objects.py
> +        self.value: str = data.get("value", None)
Why did u remove `Optional` from the typehint? clearly the `.get()` function might return `None` if the key `value` did not exist

2023-01-01 10:02 UTC, theAbdoSabbagh commented on src/DankCord/Objects.py
> +        self.authorName : str = data["author"]["name"] if "author" in data.keys() else None
Why `authorName`? `author` property already exists in that object, u can do `author.name`. Also same goes for removing `Optional` from the typehints when the value could be `None`

2023-01-01 10:02 UTC, theAbdoSabbagh commented on src/DankCord/Objects.py
> +        self.footer: Optional[EmbedFooter] = EmbedFooter(data["footer"]) if "footer" in data else None
Also here, please use `.get()` instead

2023-01-01 10:02 UTC, theAbdoSabbagh commented on src/DankCord/core.py
> +    def search(self, retry_attempts:int = 3, timeout:int = 10, location:Literal[1, 2, 3, "random"] = 2):
perhaps rename the `location` arg to `location_index` so its clearer, since without reading the code of the function even I did not understand it

2023-01-01 10:02 UTC, theAbdoSabbagh commented on src/DankCord/core.py
>          """
Add the information about the `location`/`location_index` arg to the docstring

2023-01-01 10:02 UTC, Sxvxgee commented on src/DankCord/core.py
> +            _location = location
Could be smth like:
```py
_location = location if location in [1, 2, 3, "random"] else randint(1, 3)
```

2023-01-01 10:02 UTC, Sxvxgee commented on src/DankCord/core.py
> +            _location = location
same goes here for the location code, and the docstring about the location arg, as well as renaming the arg

2023-01-01 10:03 UTC, iylun commented on src/DankCord/Objects.py
> +        self.label: str = data["label"]
oops, that must've been a mistake on my end. fixing it

2023-01-01 16:29 UTC, Sxvxgee requested changes

2023-01-01 16:29 UTC, Sxvxgee commented on src/DankCord/Objects.py
> +            self.authorName = None
This should be like this: instead 
```py
        self.authorName : str = data.get("author", {}).get("name", None)
```

2023-01-03 16:09 UTC, Sxvxgee approved these changes

2023-01-03 16:09 UTC, merged